FROM node:22-alpine

RUN corepack enable pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma/
RUN pnpm prisma generate

COPY tsconfig.json ./
COPY openapi.yaml ./
COPY prisma.config.ts ./

COPY docker-entrypoint.dev.sh ./

EXPOSE 8000

ENTRYPOINT ["sh", "docker-entrypoint.dev.sh"]
